package com.example.android.kanastrokes;

import android.media.MediaPlayer;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;
import android.widget.ImageView;

public class Hiragana_2 extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_hiragana_2);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);
        display();
    }

    public void display(){
        ImageView iv = (ImageView) findViewById(R.id.page);
        MediaPlayer play;
        switch(Hiragana_1.n){
            case 1:iv.setImageResource(R.drawable.hira_a);
                play = MediaPlayer.create(this,R.raw.a);
                play.start();
                break;
            case 2:iv.setImageResource(R.drawable.hira_i);
                play = MediaPlayer.create(this,R.raw.i);
                play.start();
                break;
            case 3:iv.setImageResource(R.drawable.hira_u);
                play = MediaPlayer.create(this,R.raw.e);
                play.start();
                break;
            case 4:iv.setImageResource(R.drawable.hira_e);
                play = MediaPlayer.create(this,R.raw.e);
                play.start();
                break;
            case 5:iv.setImageResource(R.drawable.hira_o);
                play = MediaPlayer.create(this,R.raw.o);
                play.start();
                break;
            case 6:iv.setImageResource(R.drawable.hira_ka);
                play = MediaPlayer.create(this,R.raw.ka);
                play.start();
                break;
            case 7:iv.setImageResource(R.drawable.hira_ki);
                play = MediaPlayer.create(this,R.raw.ki);
                play.start();
                break;
            case 8:iv.setImageResource(R.drawable.hira_ku);
                play = MediaPlayer.create(this,R.raw.ku);
                play.start();
                break;
            case 9:iv.setImageResource(R.drawable.hira_ke);
                play = MediaPlayer.create(this,R.raw.ke);
                play.start();
                break;
            case 10:iv.setImageResource(R.drawable.hira_ko);
                play = MediaPlayer.create(this,R.raw.ko);
                play.start();
                break;
            case 11:iv.setImageResource(R.drawable.hira_sa);
                play = MediaPlayer.create(this,R.raw.sa);
                play.start();
                break;
            case 12:iv.setImageResource(R.drawable.hira_shi);
                play = MediaPlayer.create(this,R.raw.shi);
                play.start();
                break;
            case 13:iv.setImageResource(R.drawable.hira_su);
                play = MediaPlayer.create(this,R.raw.su);
                play.start();
                break;
            case 14:iv.setImageResource(R.drawable.hira_se);
                play = MediaPlayer.create(this,R.raw.se);
                play.start();
                break;
            case 15:iv.setImageResource(R.drawable.hira_so);
                play = MediaPlayer.create(this,R.raw.so);
                play.start();
                break;
            case 16:iv.setImageResource(R.drawable.hira_ta);
                play = MediaPlayer.create(this,R.raw.ta);
                play.start();
                break;
            case 17:iv.setImageResource(R.drawable.hira_chi);
                play = MediaPlayer.create(this,R.raw.chi);
                play.start();
                break;
            case 18:iv.setImageResource(R.drawable.hira_tsu);
                play = MediaPlayer.create(this,R.raw.tsu);
                play.start();
                break;
            case 19:iv.setImageResource(R.drawable.hira_te);
                play = MediaPlayer.create(this,R.raw.te);
                play.start();
                break;
            case 20:iv.setImageResource(R.drawable.hira_to);
                play = MediaPlayer.create(this,R.raw.to);
                play.start();
                break;
            case 21:iv.setImageResource(R.drawable.hira_na);
                play = MediaPlayer.create(this,R.raw.na);
                play.start();
                break;
            case 22:iv.setImageResource(R.drawable.hira_ni);
                play = MediaPlayer.create(this,R.raw.ni);
                play.start();
                break;
            case 23:iv.setImageResource(R.drawable.hira_nu);
                play = MediaPlayer.create(this,R.raw.nu);
                play.start();
                break;
            case 24:iv.setImageResource(R.drawable.hira_ne);
                play = MediaPlayer.create(this,R.raw.ne);
                play.start();
                break;
            case 25:iv.setImageResource(R.drawable.hira_no);
                play = MediaPlayer.create(this,R.raw.no);
                play.start();
                break;
            case 26:iv.setImageResource(R.drawable.hira_ha);
                play = MediaPlayer.create(this,R.raw.ha);
                play.start();
                break;
            case 27:iv.setImageResource(R.drawable.hira_hi);
                play = MediaPlayer.create(this,R.raw.hi);
                play.start();
                break;
            case 28:iv.setImageResource(R.drawable.hira_fu);
                play = MediaPlayer.create(this,R.raw.fu);
                play.start();
                break;
            case 29:iv.setImageResource(R.drawable.hira_he);
                play = MediaPlayer.create(this,R.raw.he);
                play.start();
                break;
            case 30:iv.setImageResource(R.drawable.hira_ho);
                play = MediaPlayer.create(this,R.raw.ho);
                play.start();
                break;
            case 31:iv.setImageResource(R.drawable.hira_ma);
                play = MediaPlayer.create(this,R.raw.ma);
                play.start();
                break;
            case 32:iv.setImageResource(R.drawable.hira_mi);
                play = MediaPlayer.create(this,R.raw.mi);
                play.start();
                break;
            case 33:iv.setImageResource(R.drawable.hira_mu);
                play = MediaPlayer.create(this,R.raw.mu);
                play.start();
                break;
            case 34:iv.setImageResource(R.drawable.hira_me);
                play = MediaPlayer.create(this,R.raw.me);
                play.start();
                break;
            case 35:iv.setImageResource(R.drawable.hira_mo);
                play = MediaPlayer.create(this,R.raw.mo);
                play.start();
                break;
            case 36:iv.setImageResource(R.drawable.hira_ya);
                play = MediaPlayer.create(this,R.raw.ya);
                play.start();
                break;
            case 37:iv.setImageResource(R.drawable.hira_yu);
                play = MediaPlayer.create(this,R.raw.yu);
                play.start();
                break;
            case 38:iv.setImageResource(R.drawable.hira_yo);
                play = MediaPlayer.create(this,R.raw.yo);
                play.start();
                break;
            case 39:iv.setImageResource(R.drawable.hira_ra);
                play = MediaPlayer.create(this,R.raw.ra);
                play.start();
                break;
            case 40:iv.setImageResource(R.drawable.hira_ri);
                play = MediaPlayer.create(this,R.raw.ri);
                play.start();
                break;
            case 41:iv.setImageResource(R.drawable.hira_ru);
                play = MediaPlayer.create(this,R.raw.ru);
                play.start();
                break;
            case 42:iv.setImageResource(R.drawable.hira_re);
                play = MediaPlayer.create(this,R.raw.re);
                play.start();
                break;
            case 43:iv.setImageResource(R.drawable.hira_ro);
                play = MediaPlayer.create(this,R.raw.ro);
                play.start();
                break;
            case 44:iv.setImageResource(R.drawable.hira_wa);
                play = MediaPlayer.create(this,R.raw.wa);
                play.start();
                break;
            case 45:iv.setImageResource(R.drawable.hira_wi);
                play = MediaPlayer.create(this,R.raw.i);
                play.start();
                break;
            case 46:iv.setImageResource(R.drawable.hira_we);
                play = MediaPlayer.create(this,R.raw.e);
                play.start();
                break;
            case 47:iv.setImageResource(R.drawable.hira_wo);
                play = MediaPlayer.create(this,R.raw.wo);
                play.start();
                break;
            case 48:iv.setImageResource(R.drawable.hira_n);
                play = MediaPlayer.create(this,R.raw.n);
                play.start();
                break;
        }
    }
}
